### ISSUE TITLE
elasticsearch-remove-old-indices.sh does not work on alpine linux

### ISSUE THREAD

**Issue by servomac** [imperialwicket/elasticsearch-logstash-index-mgmt#18]
The awk expression in elasticsearch-remove-old-indices.sh does not work on Alpine Linux (musl based, http://wiki.alpinelinux.org/wiki/Awk).

Maybe can be substituted by a more simple `awk '/logstash/{print $3}'?

**Comment by imperialwicket** [comment]
Thanks for reporting.

I'm inclined to leave this as is, since my impression is that most users are running gnu awk. A couple notes:

1. I'm not actively developing this project anymore, as I'm considering it now fully superseded by Elastic's [Curator](https://github.com/elastic/curator project) (post elasticsearch 2.0, all functional goals are accommodated).
2. Anyone still using this project is theoretically running an older elasticsearch cluster, and I don't want to cause awkward breakage.
3. The awk statement itself is a little fickle, and has gone through a number of changes as elasticsearch's output formats have modified slightly over the course of this projects lifetime. I'm almost certain that the command could be simplified, but at the same time I'm positive that I don't have a good setup (or time to create one) for adequately testing the historical versions to check for potential breakage. 

@servomac - I'd recommend running a fork for the awk change, or if you want to generate a pull request that includes it, I'll put it in a separate branch/release and keep it here. Whichever you prefer.

**Comment by servomac** [comment]
Thanks for the rapid response and for contributing to the community with this script. I have been using Elasticsearch Curator and satisfies my needs.
